"""samplecode_unique

Revision ID: b684bb13514b
Revises: 4139373039d3
Create Date: 2026-08-08 17:05:54.726159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b684bb13514b'
down_revision: Union[str, None] = '4139373039d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_samples_sample_code', table_name='samples')
    op.create_index(op.f('ix_samples_sample_code'), 'samples', ['sample_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_sample_code'), table_name='samples')
    op.create_index('ix_samples_sample_code', 'samples', ['sample_code'], unique=False)
    # ### end Alembic commands ###
