"""add subject_code

Revision ID: baeda89ac4a9
Revises: e4b32bb69815
Create Date: 2026-08-06 16:50:26.378957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baeda89ac4a9'
down_revision: Union[str, None] = 'e4b32bb69815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('subject_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_samples_subject_code'), 'samples', ['subject_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_subject_code'), table_name='samples')
    op.drop_column('samples', 'subject_code')
    # ### end Alembic commands ###
